Boses:
  Demonios1:
    mundo: "hardcore"
    quantidade: "5"
    mob: "WARDEN"
    vida: "1500"
    forca: "1200"
    nameTag: "Demonio Vermelho"
    timespawn: "5" # minutos
  Demonios2:
    mundo: "hardcore"
    quantidade: "5"
    mob: "WARDEN"
    vida: "1500"
    forca: "1200"
    nameTag: "Demonio Cinza"
    timespawn: "5" # minutos
  Demonios3:
    mundo: "hardcore"
    quantidade: "10"
    mob: "PHANTOM"
    vida: "2048"
    forca: "14000"
    nameTag: "Arcanus"
    timespawn: "18" # minutos


Raid:
  Demonios1:
    mundo: "hardcore"
    mob: "ZOMBIE"
    vida: "2048"
    forca: "750"
    nameTag:
      - "tobi"
      - "zetsu"
      - "hidan"
      - "deidara"
      - "kakuzu"
      - "kisame"
      - "konan"
      - "sasori"
      - "orochimaru"
      - "itachi"
      - "pain"
    timespawn: "480" # minutos

MobsSystem:
  Fada1:
    mob: ZOMBIE
    vida: 1024
    forca: 550
    nameTag: fada

Boss:
  Mandamento1:
    mob: "ZOMBIE"
    vida: 2048
    forca: 2048
    spawnCoord: "-17785 70 -234782"
    nameTag: "derieri"
    itemUseSpawn:
      nameTag: "Spawn Boss Derieri"
      item: "PAPER"
  Mandamento2:
    mob: "ZOMBIE"
    vida: 2048
    forca: 2048
    spawnCoord: "-17785 70 -234782"
    nameTag: "drole"
    itemUseSpawn:
      nameTag: "Spawn Boss Drole"
      item: "PAPER"
  Mandamento3:
    mob: "ZOMBIE"
    vida: 2048
    forca: 2048
    spawnCoord: "-17785 70 -234782"
    nameTag: "estarossa"
    itemUseSpawn:
      nameTag: "Spawn Boss Estarossa"
      item: "PAPER"
  Mandamento4:
    mob: "ZOMBIE"
    vida: 2048
    forca: 2048
    spawnCoord: "-17785 70 -234782"
    nameTag: "fraudrin"
    itemUseSpawn:
      nameTag: "Spawn Boss Fraudrin"
      item: "PAPER"
  Mandamento5:
    mob: "ZOMBIE"
    vida: 2048
    forca: 2048
    spawnCoord: "-17785 70 -234782"
    nameTag: "galand"
    itemUseSpawn:
      nameTag: "Spawn Boss Galand"
      item: "PAPER"
  Mandamento6:
    mob: "ZOMBIE"
    vida: 2048
    forca: 2048
    spawnCoord: "-17785 70 -234782"
    nameTag: "gloxinia"
    itemUseSpawn:
      nameTag: "Spawn Boss Gloxinia"
      item: "PAPER"
  Mandamento7:
    mob: "ZOMBIE"
    vida: 2048
    forca: 2048
    spawnCoord: "-17785 70 -234782"
    nameTag: "gowther"
    itemUseSpawn:
      nameTag: "Spawn Boss Gowther"
      item: "PAPER"
  Mandamento8:
    mob: "ZOMBIE"
    vida: 2048
    forca: 2048
    spawnCoord: "-17785 70 -234782"
    nameTag: "melascula"
    itemUseSpawn:
      nameTag: "Spawn Boss Melascula"
      item: "PAPER"
  Mandamento9:
    mob: "ZOMBIE"
    vida: 2048
    forca: 2048
    spawnCoord: "-17785 70 -234782"
    nameTag: "monspiet"
    itemUseSpawn:
      nameTag: "Spawn Boss Monspiet"
      item: "PAPER"
  Mandamento10:
    mob: "ZOMBIE"
    vida: 2048
    forca: 2048
    spawnCoord: "-17785 70 -234782"
    nameTag: "zeldris"
    itemUseSpawn:
      nameTag: "Spawn Boss Zeldris"
      item: "PAPER"
  Arcanjo1:
    mob: "ZOMBIE"
    vida: 2048
    forca: 2048
    spawnCoord: "-17785 70 -234782"
    nameTag: "mael"
    itemUseSpawn:
      nameTag: "Spawn Boss Mael"
      item: "PAPER"
  Arcanjo2:
    mob: "ZOMBIE"
    vida: 2048
    forca: 2048
    spawnCoord: "-17785 70 -234782"
    nameTag: "ryudoshel"
    itemUseSpawn:
      nameTag: "Spawn Boss Ryudoshel"
      item: "PAPER"
  Arcanjo3:
    mob: "ZOMBIE"
    vida: 2048
    forca: 2048
    spawnCoord: "-17785 70 -234782"
    nameTag: "sariel"
    itemUseSpawn:
      nameTag: "Spawn Boss Sariel"
      item: "PAPER"
  Arcanjo4:
    mob: "ZOMBIE"
    vida: 2048
    forca: 2048
    spawnCoord: "-17785 70 -234782"
    nameTag: "tarmiel"
    itemUseSpawn:
      nameTag: "Spawn Boss Tarmiel"
      item: "PAPER"

Pecados:
  1:
    mob: "ZOMBIE"
    vida: 2048
    forca: 2048
    spawnCoord: "-17310 101 -235868"
    nameTag: "ban"
  2:
    mob: "ZOMBIE"
    vida: 2048
    forca: 2048
    spawnCoord: "-17310 101 -235868"
    nameTag: "escanor"
  3:
    mob: "ZOMBIE"
    vida: 2048
    forca: 2048
    spawnCoord: "-17310 101 -235868"
    nameTag: "merlin"
  4:
    mob: "ZOMBIE"
    vida: 2048
    forca: 2048
    spawnCoord: "-17310 101 -235868"
    nameTag: "gowther"
  5:
    mob: "ZOMBIE"
    vida: 2048
    forca: 2048
    spawnCoord: "-17310 101 -235868"
    nameTag: "meliodas"
  6:
    mob: "ZOMBIE"
    vida: 2048
    forca: 2048
    spawnCoord: "-17310 101 -235868"
    nameTag: "diane"
  7:
    mob: "ZOMBIE"
    vida: 2048
    forca: 2048
    spawnCoord: "-17310 101 -235868"
    nameTag: "king"

Drops:
  1:
    mob: "PHANTOM"
    mobNameTag: "Arcanus"
    itemDrop: "NETHER_STAR"
    itemDisplayName: "Estrela da Sorte"
    chanceDrop: 10